name: Keepalive

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: keepalive
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Jitter (avoid thundering herd)
        run: sleep $((RANDOM % 60))

      - name: Ping Streamlit app
        run: |
          set -euo pipefail
          urls=(
            "https://pses-explorer.streamlit.app/"
          )
          for u in "${urls[@]}"; do
            echo "Pinging: $u"
            curl -sS --fail --max-time 20 --retry 3 --retry-delay 5 "$u" > /dev/null
            echo "OK"
          done
